plugin: aws_ec2
regions:
  - us-west-2
include_filters:
  - instance-state-name : running
exclude_filters:
  - tag:kind:
    - 'ansible'
keyed_groups:
  - key: tags.kind
    separator: ""
hostnames:
  - tag:Name
  - private-ip-address
compose:
  ansible_host: private_ip_address