- name: apt update
  ansible.builtin.apt:
    update_cache: yes

- name: Install Jq
  ansible.builtin.apt:
    name: jq

- name: Install aws cli
  ansible.builtin.shell:
    cmd: |
      apt install zip -y
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
      unzip /tmp/awscliv2.zip -d /tmp
      /tmp/aws/install
      aws --version