- name: "curl:  bastion server -> apache server 8080 port"
  ansible.builtin.shell:
    cmd: |
      curl http://{{apache_server_ip}}:8080
  register: result

- debug:
    var: result
    verbosity: 1

# - name: "check result"
#   ansible.builtin.assert:
#     that:
#       - result

