- name: "各ユーザーで踏み台へのSSH接続確認"
  ansible.builtin.shell:
    cmd: |
      ssh {{user.name}}@{{ hostvars[groups['bastion'][0]].public_ip_address }} -i /home/ubuntu/user_keys/{{user.name}}/id_rsa -o "StrictHostKeyChecking no" id
  register: result
  loop: "{{ hostvars[groups['bastion'][0]].personal_users }}"
  loop_control:
    loop_var: user

- debug:
    var: "result"
    verbosity: 1

- name: "check result"
  ansible.builtin.assert:
    that:
      - "'uid' in ssh_result.stdout"
      - ssh_result.rc == 0
    success_msg: "[{{ ssh_result.cmd }}] successed."
    fail_msg: "[{{ ssh_result.cmd }}] failed."
  loop: "{{ result.results }}"
  loop_control:
    loop_var: ssh_result